### ISSUE TITLE
The backright swerve modules will not spin sometimes

### ISSUE THREAD

**Issue by PandaBear904** [PandaBear904/Robot-Code-2024#2]
When I was messing with the swerve modules json the back right would stop spinning and I found a way around it by making new json files and inputting them into the code

**Comment by lasaldan** [comment]
Nice work. Would you say this issue is resolved by your fix?

I believe the commit with the fix would be: https://github.com/PandaBear904/Robot-Code-2024/commit/00248ddaf0a5f37cb5f25695189f9bff0fbbac54

Also related: https://github.com/PandaBear904/Robot-Code-2024/commit/de0ffa96345c6413a70866c2cb7e42099df31be6 and https://github.com/PandaBear904/Robot-Code-2024/commit/82474ed8b9ac2cf5aa5522ef9b226a3caa78e21a
